version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
  client:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
  mysql-master:
    container_name: mysql-master
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buku
      MYSQL_USER: app
      MYSQL_PASSWORD: root
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    volumes:
      - ./mysql-data:/var/lib/mysql
  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    depends_on:
      - mysql-master
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buku
      MYSQL_USER: app
      MYSQL_PASSWORD: root
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
volumes:
  mysql-data: {}
